Handle overlapping routes with different RegExes
gsquire/reroute pull request #16
Opened 2016-12-09 01:25 UTC by rpjohnst

I have two routes based on different `RegEx` strings that can match the same path, but with different methods. Depending on their ordering, current `reroute` forces one to respond with a 405, because it only looks in its route table for the first matching `RegEx` string.

(For context, the two routes are `OPTIONS` with `.*$` and `GET` with `/something/specific$`, where the `OPTIONS` route is a generic CORS handler for several other endpoints.)

I don't know that this is the best solution, precedence or performance-wise, but I don't have a lot of experience with other router APIs and how they solve this problem, so I'd like to see what others think here. This PR just loops over all matching `RegEx`es rather than failing if the first one's method doesn't match the request.

2016-12-09 18:02 UTC, gsquire commented
You raise a good point with this PR. This is something that hadn't occurred to me with some simple testing. It LGTM overall but I think I want to take it a step further and try and knock out #14 too.

I think with your addition of checking each match it would be good to see if we can catch `/` matching everything by checking the length of the route path.

Perhaps something like this:
```rust
if route == "/" && uri.len() > 1 {
    continue;
}
```
Let me know if this makes sense or not.

2016-12-10 19:26 UTC, rpjohnst commented
Okay, I've done some research on how other routing APIs handle this problem.

The solution to the `/` problem seems to be simply anchoring the `RegEx`es at the end as well as the beginning- no need to hardcode anything and it's a more general solution. One tweak we could do on top is to add `\/?` like express.js does (via `path-to-regexp`).

There are also options for disambiguating routes beyond just the order they were added- express.js takes a callback for each named parameter to validate it before accepting a route, and Conduit/Iron's `route-recognizer` orders routes by number of `*param`, `:param`, and static path elements. These both require named parameter support, but aren't really necessary either.

Performance-wise, `route-recognizer` uses a custom NFA implementation `Router<T>` that matches multiple routes at once *and* collects captures as it goes. Conduit uses a `HashMap<Method, Router<Handler>>`, while Iron uses `Router<HashMap<Method, Handler>>`.

The first solution involves no looping over candidates, but does duplicate the matcher. This is equivalent to including the method in the `RegEx`es, which in our case is even worse- not only does the `RegexSet` get bigger, we also duplicate stand-alone `RegEx`es for each method (which we currently do anyway).

The second has only one matcher (and in our case fewer `RegEx`es), but requires a linear search to find a route with the right method. I think I'd like to go with this method, which is equivalent to this PR though a little better-organized.

Thoughts?

2016-12-11 19:40 UTC, gsquire commented
I am fine with the second option like you said. It also never occurred to me that you could add `/Z` to the routes as well. I wonder if this will cause any performance hits to the `RegexSet`.

Also, thanks so much for the research. I have used Iron's router when I built something with Iron and I know the routing is done quite differently than in reroute's approach.

Let me know if you need any help with this.

2016-12-13 03:26 UTC, rpjohnst commented
Alright, here's an update. The main change is from a `HashMap<RouteInfo, Handler>` to a `Vec<(Method, Handler)>`. I didn't wind up coalescing the regexes routes that use the same string because that doesn't preserve insertion order, and reroute already duplicates compiled regexes. Maybe we can find a solution to that later.

I also switched to the builder pattern, to cut down on the amount of redundant state in the router, and simplified the error type since it turns out `regex` as of `0.1.59` supports `RegexSet`s with 0 entries. That makes this a breaking change, not sure what you feel about that in this situation.

2016-12-13 17:40 UTC, gsquire requested changes
This looks awesome. My comments are trivial so I can merge this pretty soon after. I will also go back and add doc comments to the public functions.

2016-12-13 17:40 UTC, gsquire commented on Cargo.toml
> +regex = "0.1.59"
Is there a specific reason you used this version? I was able to compile with 0.1.80 just fine.

2016-12-13 17:40 UTC, gsquire commented on src/error.rs
> +use regex;
Since we are just referring to the regex package's error type, can we omit the `use` statement and just refer to it as `::regex::Error`?

2016-12-13 17:40 UTC, gsquire commented on src/lib.rs
> +    regexes: Vec<Regex>,
Can we call this `patterns`?

2016-12-13 17:40 UTC, gsquire commented on src/lib.rs
> +        // anchor at the start and end so routes only match exactly
Kind of pedantic, but I like to make my comments sentences.

2016-12-13 20:19 UTC, rpjohnst commented on Cargo.toml
> +regex = "0.1.59"
Yeah, this is the minimum required version since it supports 0-entry `RegexSet`s- Cargo will pull `0.1.80` for new projects since it's semver-compatible with `0.1.59`.

2016-12-13 21:26 UTC, gsquire approved these changes

2016-12-13 21:28 UTC, gsquire commented
Thanks so much for this PR. I will publish a new release soon after.

Closes #14

2016-12-13 21:29 UTC, merged